version: "2"
services:

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ProjectX
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    restart: always
    image: sbrkrkmz/project-x-api
    depends_on:
      - db
    build: ./
    links:
      - db
    ports:
      - "5555:5555"
